import img1 from '../../assets/image/Karen.jpg'
import img2 from '../../assets/image/anrew.jpg'
import img3 from '../../assets/image/Oval.jpg'
import img4 from '../../assets/image/Maximillian Jacobson.jpg'
import img5 from '../../assets/image/Oval (1).jpg'
import img6 from '../../assets/image/Oval (2).jpg'
import img7 from '../../assets/image/Oval (3).jpg'

export const chat = [
    {
        id:'1',
        user:{
            name:'ALex',
            img:img7
        },
        lastMessage:{
            text:'hello',
            date:'07:30'
        }
    },
    {
        id:'2',
        user:{
            name:'Lukas',
            img:img2
        },
        lastMessage:{
            text:'Hi',
            date:'09:40'
        }
    },
    {
        id:'3',
        user:{
            name:'Karen',
            img:img3
        },
        lastMessage:{
            text:'last to',
            date:'09:40'
        }
    },
    {
        id:'4',
        user:{
            name:'Kari',
            img:img2
        },
        lastMessage:{
            text:'Hsdvfvbf',
            date:'09:40'
        }
    },{
        id:'5',
        user:{
            name:'Minis',
            img:img5
        },
        lastMessage:{
            text:'Save',
            date:'14:40'
        }
    },{
        id:'6',
        user:{
            name:'Maki',
            img:img6
        },
        lastMessage:{
            text:'CS-Go',
            date:'14:04'
        }
    },
    {
        id:'7',
        user:{
            name:'Marat',
            img:img7
        },
        lastMessage:{
            text:'Analgin',
            date:'13:04'
        }
    },
    {
        id:'8',
        user:{
            name:'Kari',
            img:img2
        },
        lastMessage:{
            text:'😂😂😂😂😂😂',
            date:'09:40'
        }
    },{
        id:'9',
        user:{
            name:'Minis',
            img:img5
        },
        lastMessage:{
            text:'Save',
            date:'14:40'
        }
    },{
        id:'10',
        user:{
            name:'Maki',
            img:img6
        },
        lastMessage:{
            text:'CS-Go',
            date:'14:04'
        }
    },
    {
        id:'11',
        user:{
            name:'Marat',
            img:img7
        },
        lastMessage:{
            text:'😢😢😢',
            date:'13:04'
        }
    },


]